version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env
    ports:
      - '9000:27017'
    volumes:
      - mongodb:/data/db

  web:
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - ./app.env
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb

volumes:
  mongodb:
